networks:
  kafka-network:
    driver: bridge

services:
    kafka: 
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
            KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
            KAFKA_LISTENER_NAME: PLAINTEXT
            KAFKA_KRAFT_MODE: "true"  # Enabling KRaft mode
            KAFKA_LISTENER_PORT: 9092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092  # This is the internal listener for other containers to access
            KAFKA_LISTENER_INTERNAL: INSIDE://0.0.0.0:9092  # Internal listener for other containers
            KAFKA_ZOOKEEPER: ""  # No Zookeeper since we're using KRaft mode
        ports:
        - "9092:9092"  # Expose port for external access (optional)